mattermost-models/src/main/java/net/bis5/mattermost/model/SwitchRequest.java
mattermost4j/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

change SwitchRequest.currentPassword to password for Mattermost 4.0's change

---

mattermost-models/src/main/java/net/bis5/mattermost/model/ContentType.java
mattermost-models/src/main/java/net/bis5/mattermost/model/IncomingWebhook.java
mattermost-models/src/main/java/net/bis5/mattermost/model/IncomingWebhookList.java
mattermost-models/src/main/java/net/bis5/mattermost/model/OutgoingWebhook.java
mattermost-models/src/main/java/net/bis5/mattermost/model/OutgoingWebhookList.java
mattermost-models/src/main/java/net/bis5/mattermost/model/TriggerWhen.java
mattermost4j/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j/src/main/java/net/bis5/mattermost/client4/api/WebhookApi.java
mattermost4j/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java
mattermost4j/src/test/java/net/bis5/mattermost/client4/TestHelper.java

#13 test webhooks api

---

mattermost-models/src/main/java/net/bis5/mattermost/model/Config.java
mattermost-models/src/main/java/net/bis5/mattermost/model/config/ElasticsearchSettings.java
mattermost-models/src/main/java/net/bis5/mattermost/model/config/EmailSettings.java
mattermost-models/src/main/java/net/bis5/mattermost/model/config/FileSettings.java
mattermost-models/src/main/java/net/bis5/mattermost/model/config/JobSettings.java
mattermost-models/src/main/java/net/bis5/mattermost/model/config/ServiceSettings.java
mattermost-models/src/main/java/net/bis5/mattermost/model/config/TeamSettings.java
mattermost-models/src/main/java/net/bis5/mattermost/model/config/ThemeSettings.java
mattermost-models/src/main/java/net/bis5/mattermost/model/config/consts/EmailNotificationContent.java

Add configurations

---

mattermost-models/src/main/java/net/bis5/mattermost/model/PostAction.java

Add missing properties for Mattermost Server 5.4

---

mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/ChannelApi.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

Add Channel Restore API

---

mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/ChannelApi.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

Add Get Deleted Channels API

---

mattermost4j-core/pom.xml
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/EmojiApi.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

Add Get Custom Emoji Image API

---

mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

Add test case for GetFlaggedPostsForUser and fix it

---

mattermost-models/src/main/java/net/bis5/mattermost/model/AnalyticsRows.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/GeneralApi.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/model/AnalyticsCategory.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

Add Get Analytics API

---

.circleci/config.yml
.circleci/settings-sonar.xml
README.md
pom.xml

Scan only. 
We can add report to PRs from SonarQube with additional configurations.

Setup SonarQube

---

mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java

Remove unnecessary throws declaration from MattermostClient#close

---

mattermost-models/src/main/java/net/bis5/mattermost/model/PostAction.java

Add PostActionIntegrationRequet.triggerId property

---

mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java
pom.xml

Use JUnit 5

---

mattermost-models/src/main/java/net/bis5/mattermost/model/StatusType.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

Fix typo: StatusType.ARAY -> AWAY

---

mattermost-models/src/main/java/net/bis5/mattermost/model/UserAccessToken.java
mattermost-models/src/main/java/net/bis5/mattermost/model/UserAccessTokenList.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/UserApi.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/model/DisableEnableTokenRequest.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/model/RevokeTokenRequest.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/model/SearchTokensRequest.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/model/UserAccessTokenCreateRequest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/TestHelper.java

Add APIs related to User Access Token

---

mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/TestHelper.java

Add Tests for System API

---

README.md
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/main/java/net/bis5/mattermost/jersey/provider/MattermostModelMapperProvider.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/TestHelper.java
mattermost4j-core/src/test/java/net/bis5/mattermost/jersey/provider/MattermostModelMapperProviderTest.java

When Mattermost Server api response changed, you can suppress JsonMappingException by ignoreUnknownProperties = true by using MattermostClientBuilder#ignoreUnknownProperties().

Add ignoreUnknownProperties option

---

mattermost-models/src/main/java/net/bis5/mattermost/model/Config.java
mattermost-models/src/main/java/net/bis5/mattermost/model/PostType.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/ApiResponse.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java

Fix javadoc errors

---

mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/BrandApi.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

Implement Brand API

---

mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

Ignore custom branding not supported failure for esr

---

mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/PostApi.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

Add PostApi#getFileInfoForPost

---

mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/UserApi.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

Add UserApi#revokeAllActiveSessionForUser

---

mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/EmojiApi.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

Add EmojiApi#getEmojiByName

---

mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/EmojiApi.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/model/SearchEmojiRequest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

Add EmojiApi#searchEmoji

---

mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/EmojiApi.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

Add EmojiApi#autocompleteEmoji

---

mattermost-models/src/main/java/net/bis5/mattermost/model/TeamInviteInfo.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/TeamApi.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/TestHelper.java

Add TeamApi#getInviteInfo

---

mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/TeamApi.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

Add team icon apis

---

mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/ChannelApi.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

Add ChannelApi#convertChannelToPrivate

---

mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/BrandApi.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

Add BrandApi#deleteBrandImage

---

mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/UserApi.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

Add UserApi#deleteProfileImage

---

mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/PostApi.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

Change OffsetDateTime to ZonedDateTime

---

mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/ClusterApi.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

Add cluster api test and fix it

---

mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/ElasticsearchApi.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

Add ElasticsearchApi

---

mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/PostApi.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/model/CreateEphemeralPostRequest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

add Create Ephemeral Post API

---

.circleci/config.yml

Bump jdk for ci and remove workaround options

---

mattermost-models/src/main/java/net/bis5/mattermost/model/WebrtcInfoResponse.java
mattermost-models/src/main/java/net/bis5/mattermost/model/config/WebrtcSettings.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/WebrtcApi.java

Deprecate WebRTC

---

mattermost-models/src/main/java/net/bis5/mattermost/model/PostType.java

Add missing post types

---

mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/SystemApi.java

Rename GeneralApi to SystemApi.

---

mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/SamlApi.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

Add support for SAML APIs

---

mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

Add test cases for LDAP apis

---

mattermost4j-core/pom.xml
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/OpenGraphApi.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

Implement OpenGraph API

---

mattermost-models/src/main/java/net/bis5/mattermost/model/UserPatch.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

Add missing properties to UserPatch

---

mattermost-models/src/main/java/net/bis5/mattermost/model/Bot.java
mattermost-models/src/main/java/net/bis5/mattermost/model/BotPatch.java
mattermost-models/src/main/java/net/bis5/mattermost/model/Bots.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/QueryBuilder.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/BotsApi.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/model/GetBotsOption.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java

Add bots API (#244)

---

.circleci/config.yml

ci: drop 4.10.x test (#267)

---

mattermost-models/src/main/java/net/bis5/mattermost/model/config/AnalyticsSettings.java
mattermost-models/src/main/java/net/bis5/mattermost/model/config/ClientRequirements.java
mattermost-models/src/main/java/net/bis5/mattermost/model/config/ClusterSettings.java
mattermost-models/src/main/java/net/bis5/mattermost/model/config/ComplianceSettings.java
mattermost-models/src/main/java/net/bis5/mattermost/model/config/DataRetentionSettings.java
mattermost-models/src/main/java/net/bis5/mattermost/model/config/DisplaySettings.java
mattermost-models/src/main/java/net/bis5/mattermost/model/config/ElasticsearchSettings.java
mattermost-models/src/main/java/net/bis5/mattermost/model/config/GlobalRelayMessageExportSettings.java
mattermost-models/src/main/java/net/bis5/mattermost/model/config/JobSettings.java
mattermost-models/src/main/java/net/bis5/mattermost/model/config/LocalizationSettings.java
mattermost-models/src/main/java/net/bis5/mattermost/model/config/MessageExportSettings.java
mattermost-models/src/main/java/net/bis5/mattermost/model/config/MetricsSettings.java
mattermost-models/src/main/java/net/bis5/mattermost/model/config/NativeAppSettings.java
mattermost-models/src/main/java/net/bis5/mattermost/model/config/PluginSettings.java
mattermost-models/src/main/java/net/bis5/mattermost/model/config/SamlSettings.java
mattermost-models/src/main/java/net/bis5/mattermost/model/config/ThemeSettings.java

fix: Add missing configuration properties

---

.circleci/config.yml
README.md
docker-compose.yml
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/MattermostApiTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/TestHelper.java

chore: Add docker-compose.yml (#310)

---

mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/ChannelApi.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/api/ChannelsApiTest.java

feat: add channels autocomplete api

---

mattermost4j-core/src/main/java/net/bis5/mattermost/client4/MattermostClient.java
mattermost4j-core/src/main/java/net/bis5/mattermost/client4/api/EmojiApi.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/api/EmojiApiTest.java

feat: add support to get custom emoji list sort by name

---

mattermost4j-core/src/main/java/net/bis5/mattermost/client4/ApiResponse.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/ApiResponseTest.java

fix: detect response content-type correctly if charset present

---

README.md

Hi, there is a typo in the WebhookClient Sample code

add missing semicolon

---

mattermost4j-core/src/test/java/net/bis5/mattermost/client4/HttpConfigTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/api/BotsApiTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/api/BrandApiTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/api/ChannelsApiTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/api/ClusterApiTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/api/CommandsApiTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/api/ElasticsearchApiTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/api/EmojiApiTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/api/FilesApiTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/api/IncomingWebhookClientTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/api/LdapApiTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/api/OpenGraphApiTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/api/PluginApiTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/api/PostsApiTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/api/PreferencesApiTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/api/ReactionApiTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/api/SamlApiTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/api/StatusApiTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/api/SystemApiTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/api/TeamsApiTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/api/UsersApiTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/client4/api/WebhooksApiTest.java
mattermost4j-core/src/test/java/net/bis5/mattermost/jersey/provider/MattermostModelMapperProviderTest.java

Remove unnecessary "public" modifiers (#366)

---

mattermost-models/src/main/java/net/bis5/mattermost/model/Team.java

add cloudLimitsArchived for Mattermost Server 7.1.0

feat: Add Team.cloudLimitsArchived
